<script>

</script>
<template>
    <!-- *******LOADING******* -->
    <div class="bg" id="loading">
        <div class="loadingio-spinner-double-ring-cm1ltjai5mu"><div class="ldio-ujurhm9bi0c">
            <div></div>
            <div></div>
            <div><div></div></div>
            <div><div></div></div>
        </div></div>
    </div>
    <!-- *******LOADING-END******* -->
</template>
<style scoped>
.bg{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgb(255, 255, 255);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 99;
}
@keyframes ldio-ujurhm9bi0c {
      0% { transform: rotate(0) }
      100% { transform: rotate(360deg) }
}
    .ldio-ujurhm9bi0c div { box-sizing: border-box!important }
    .ldio-ujurhm9bi0c > div {
      position: absolute;
      width: 130.2px;
      height: 130.2px;
      top: 43.4px;
      left: 43.4px;
      border-radius: 50%;
      border: 13.02px solid #000;
      border-color: #00a650 transparent #00a650 transparent;
      animation: ldio-ujurhm9bi0c 2.272727272727273s linear infinite;
    }
    
    .ldio-ujurhm9bi0c > div:nth-child(2), .ldio-ujurhm9bi0c > div:nth-child(4) {
      width: 99.82px;
      height: 99.82px;
      top: 58.589999999999996px;
      left: 58.589999999999996px;
      animation: ldio-ujurhm9bi0c 2.272727272727273s linear infinite reverse;
    }
    .ldio-ujurhm9bi0c > div:nth-child(2) {
      border-color: transparent #00405a transparent #00405a
    }
    .ldio-ujurhm9bi0c > div:nth-child(3) { border-color: transparent }
    .ldio-ujurhm9bi0c > div:nth-child(3) div {
      position: absolute;
      width: 100%;
      height: 100%;
      transform: rotate(45deg);
    }
    .ldio-ujurhm9bi0c > div:nth-child(3) div:before, .ldio-ujurhm9bi0c > div:nth-child(3) div:after { 
      content: "";
      display: block;
      position: absolute;
      width: 13.02px;
      height: 13.02px;
      top: -13.02px;
      left: 45.57px;
      background: #00a650;
      border-radius: 50%;
      box-shadow: 0 117.17999999999999px 0 0 #00a650;
    }
    .ldio-ujurhm9bi0c > div:nth-child(3) div:after {
      left: -13.02px;
      top: 45.57px;
      box-shadow: 117.17999999999999px 0 0 0 #00a650;
    }
    
    .ldio-ujurhm9bi0c > div:nth-child(4) { border-color: transparent; }
    .ldio-ujurhm9bi0c > div:nth-child(4) div {
      position: absolute;
      width: 100%;
      height: 100%;
      transform: rotate(45deg);
    }
    .ldio-ujurhm9bi0c > div:nth-child(4) div:before, .ldio-ujurhm9bi0c > div:nth-child(4) div:after {
      content: "";
      display: block;
      position: absolute;
      width: 13.02px;
      height: 13.02px;
      top: -13.02px;
      left: 30.38px;
      background: #00405a;
      border-radius: 50%;
      box-shadow: 0 86.8px 0 0 #00405a;
    }
    .ldio-ujurhm9bi0c > div:nth-child(4) div:after {
      left: -13.02px;
      top: 30.38px;
      box-shadow: 86.8px 0 0 0 #00405a;
    }
    .loadingio-spinner-double-ring-cm1ltjai5mu {
      width: 217px;
      height: 217px;
      display: inline-block;
      overflow: hidden;
    }
    .ldio-ujurhm9bi0c {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-ujurhm9bi0c div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>